version: "2"
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "mHsJ33lF+1FZ"
      MYSQL_DATABASE: "rmtest"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "mHsJ33lF+1FZ"
    ports:
      - "127.0.0.1:3306:3306"
